output_dir: DIR

data:
    name: cosmo
    data_dir: DIR
    n_train: 100
    n_valid: 0
    sample_shape: [128, 128, 128, 4]
    batch_size: 4
    n_epochs: 2
    shard: True
    apply_log: True
    prefetch: 4

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    conv_size: 32
    fc1_size: 128
    fc2_size: 64
    hidden_activation: LeakyReLU
    pooling_type: MaxPool3D
    dropout: 0.5

optimizer:
    name: SGD
    lr: 0.01
    momentum: 0.9
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
    lr_schedule:
        32: 0.1
        64: 0.1
    early_stopping_patience: 8