output_dir: /gpfs/alpine/world-shared/stf011/atsaris/cosmoflow_output_2020/

data:
    name: cosmo
    data_dir: /gpfs/alpine/world-shared/stf011/atsaris/cosmoflow_data_2020/cosmoUniverse_2019_05_4parE_tf_test/
    n_train: 256
    n_valid: 0
    samples_per_file: 64
    shard: True
    sample_shape: [128, 128, 128, 4]
    batch_size: 1
    n_epochs: 64

model:
    name: cosmoflow
    input_shape: [128, 128, 128, 4]
    target_size: 4
    dropout: 0.2

optimizer:
    name: Adadelta
    lr: 0.5
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']